#bucket_name = "bucket-for-statefile-48693"    # Put the desired GCS Bucket name.
project_name = "mission-gcp-certification"
region = "us-central1"
zone = "us-central1-a"
vpc_name = "uat-vpc"
public_subnet_rang = "172.0.0.0/24"
private_subnet_rang = "172.2.0.0/24"
environment = "uat-testing"
machine_type = "e2-medium"
